/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.SanPhamDAO;
import entity.SanPham;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BanhMi88
 */
public class JFrame_BangNhapExcel extends javax.swing.JFrame {

    /**
     * Creates new form TablePopUp
     *
     * @param object
     * @param title
     */
    private SanPham sanPham;
    private final SanPhamDAO sanPhamDAO = new SanPhamDAO();

    public JFrame_BangNhapExcel(List<Object[]> object, Object[] title) {
        initComponents();

        DefaultTableModel model = new DefaultTableModel(new Object[][]{}, title);
        tablePopup.setModel(model);
        DefaultTableModel modelExcel = (DefaultTableModel) tablePopup.getModel();
        modelExcel.setRowCount(0);
        for (Object[] rowData : object) {
            model.addRow(rowData);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPopup = new javax.swing.JScrollPane();
        tablePopup = new javax.swing.JTable();
        function = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1167, 600));
        setUndecorated(true);

        scrollPopup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        scrollPopup.setPreferredSize(new java.awt.Dimension(1100, 400));

        tablePopup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePopup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollPopup.setViewportView(tablePopup);

        getContentPane().add(scrollPopup, java.awt.BorderLayout.CENTER);

        function.setMinimumSize(new java.awt.Dimension(1000, 100));
        function.setPreferredSize(new java.awt.Dimension(1160, 90));

        btnThem.setBackground(new java.awt.Color(0, 122, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm dữ liệu");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 0, 0));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout functionLayout = new javax.swing.GroupLayout(function);
        function.setLayout(functionLayout);
        functionLayout.setHorizontalGroup(
            functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, functionLayout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
        );
        functionLayout.setVerticalGroup(
            functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(functionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(functionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(function, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DỮ LIỆU NHẬP");
        jLabel1.setPreferredSize(new java.awt.Dimension(282, 70));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        int[] selectedRows = tablePopup.getSelectedRows();
        int messageSP = 0;
        int messageNCC = 0;
        int thanhCong = 0;
        DefaultTableModel modelExcel = (DefaultTableModel) tablePopup.getModel();
        List<Integer> rowsToRemove = new ArrayList<>();
        if (selectedRows.length <= 0) {
            for (int i = 0; i < tablePopup.getRowCount(); i++) {
                Object[] rowData = new Object[tablePopup.getColumnCount()];
                for (int j = 0; j < tablePopup.getColumnCount(); j++) {
                    rowData[j] = tablePopup.getValueAt(i, j);
                }
                sanPham = new SanPham(rowData);
                int result = sanPhamDAO.themTuExcell(sanPham);
                switch (result) {
                    case 1:
                        messageSP++;
                        break;
                    case 2:
                        messageNCC++;
                        break;
                    case 3:
                        thanhCong++;
                        rowsToRemove.add(i);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Lỗi");
                }
            }
        } else {
            for (int i : selectedRows) {
                Object[] rowData = new Object[tablePopup.getColumnCount()];
                for (int j = 0; j < tablePopup.getColumnCount(); j++) {
                    rowData[j] = tablePopup.getValueAt(i, j);
                }
                sanPham = new SanPham(rowData);
                int result = sanPhamDAO.themTuExcell(sanPham);
                switch (result) {
                    case 1:
                        messageSP++;
                        break;
                    case 2:
                        messageNCC++;
                        break;
                    case 3:
                        thanhCong++;
                        rowsToRemove.add(i);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Lỗi");
                }
            }
        }

        // Đảo ngược mảng để xoá từ dòng cuối lên dòng đầu tránh gây lỗi
        Collections.reverse(rowsToRemove);
        for (int i : rowsToRemove) {
            modelExcel.removeRow(i);
        }

        String message = "";
        if (thanhCong != 0) {
            message += "Có " + thanhCong + " sản phẩm thêm thành công\n";
        }
        if (messageSP != 0) {
            message += "Có " + messageSP + " sản phẩm không thể thêm do trùng mã\n";
        }
        if (messageNCC != 0) {
            message += "Có " + messageNCC + " sản phẩm không thể thêm không tồn tại nhà cung cấp";
        }
        JOptionPane.showMessageDialog(null, message);

    }//GEN-LAST:event_btnThemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JPanel function;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollPopup;
    private javax.swing.JTable tablePopup;
    // End of variables declaration//GEN-END:variables
}
