package gui;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.PlanarYUVLuminanceSource;
import com.google.zxing.Reader;
import com.google.zxing.Result;
import com.google.zxing.common.HybridBinarizer;
import dao.ChiTietHoaDonDAO;
import dao.HoaDonDAO;
import dao.KhachHangDAO;
import dao.SanPhamDAO;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 * @author Nguyễn Thanh Nhứt
 */
public class JPanel_BanHang extends javax.swing.JPanel {
    
    private String maNhanVien;
    private DefaultTableModel modelCart;
    private SanPhamDAO sanPhamDAO = new SanPhamDAO();
    private HoaDonDAO hoaDonDAO = new HoaDonDAO();
    private KhachHangDAO khachHangDAO = new KhachHangDAO();
    private ChiTietHoaDonDAO chiTietHoaDonDAO = new ChiTietHoaDonDAO();
    private NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
    private DecimalFormat decimalFormat = new DecimalFormat("#,###");
    private int infoPage = 1;
    private int infoPageCategory;

    public JPanel_BanHang(String maNhanVien) {
        this.maNhanVien = maNhanVien;
        initComponents();
        modelCart = (DefaultTableModel) tbl_Cart.getModel();
        modelCart.setRowCount(0);
        svgPay2.setSvgImage("pay.svg", 30, 30);
        svgPay1.setSvgImage("pay.svg", 30, 30);
        svgSearch.setSvgImage("search.svg", 20, 20);
        svgCreateInvoice.setSvgImage("add.svg", 20, 20);
        svgDelete.setSvgImage("delete.svg", 20, 20);
        svgDeleteAll.setSvgImage("delete.svg", 20, 20);
        
        svgReload.setSvgImage("refresh.svg", 20, 20);

//        jpPaySale.setEnabled(false);
//        txt_customerMoneyGive.setEnabled(false);
//        txa_noteSale.setEnabled(false);
//        cb_customerIdSale.setEnabled(false);
//
//        jpDelivery.setEnabled(false);
//        txt_customerPhone.setEnabled(false);
//        txa_customerDeliveryAddress.setEnabled(false);
//        txa_noteOrder.setEnabled(false);
        
        Thread thread = new Thread(
                () -> scanCode()
        );
        thread.start();
       
    }

    public void scanCode() {
        Webcam webcam = Webcam.getDefault();
        webcam.open();

        WebcamPanel webcamPanel = new WebcamPanel(webcam);
        webcamPanel.setFPSDisplayed(true);
        webcamPanel.setDisplayDebugInfo(true);
        webcamPanel.setImageSizeDisplayed(true);
        webcamPanel.setMirrored(false); // Đừng đảo ngược hình ảnh

        jPanelScanCode.add(webcamPanel, BorderLayout.CENTER);
        jPanelScanCode.repaint();
        jPanelScanCode.revalidate();
        while (true) {
            BufferedImage image = webcam.getImage();
            Result result = decodeBarcode(image);
            if (result != null) {
                jTextFieldValueSearchProduct.setText(result.getText());
            }
        }
    }

    private static Result decodeBarcode(BufferedImage image) {
        try {
            int width = image.getWidth();
            int height = image.getHeight();
            int[] pixels = new int[width * height];
            image.getRGB(0, 0, width, height, pixels, 0, width);

            LuminanceSource source = new PlanarYUVLuminanceSource(
                    toByteArray(pixels, width, height),
                    width,
                    height,
                    0,
                    0,
                    width,
                    height,
                    false
            );

            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            Reader reader = new MultiFormatReader();
            return reader.decode(bitmap);
        } catch (NotFoundException e) {
            // Không tìm thấy mã vạch
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private static byte[] toByteArray(int[] pixels, int width, int height) {
        byte[] byteArray = new byte[width * height];
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                int pixel = pixels[i * width + j];
                byteArray[i * width + j] = (byte) ((pixel >> 16) & 0xFF);
            }
        }
        return byteArray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScanCode = new javax.swing.JPanel();
        jPanelCart = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Cart = new javax.swing.JTable();
        jTextFieldValueSearchProduct = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        lblSearchProduct = new javax.swing.JLabel();
        jComboBoxValueCategory = new javax.swing.JComboBox<>();
        jButtonRefresh3 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelOrderPay = new javax.swing.JPanel();
        jpPay1 = new util.JPanelRounded();
        lblPay1 = new javax.swing.JLabel();
        svgPay1 = new util.SVGImage();
        jPanel2 = new javax.swing.JPanel();
        lblTotalAmount = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblMustPay = new javax.swing.JLabel();
        lblCustomerMoneyGive = new javax.swing.JLabel();
        lblReturnMoneyToCustomer = new javax.swing.JLabel();
        jTextFieldValueCustomerMoneyGive = new javax.swing.JTextField();
        lblValueReturnMoneyToCustomer = new javax.swing.JLabel();
        lblUnit5 = new javax.swing.JLabel();
        lblUnit4 = new javax.swing.JLabel();
        lblUnit3 = new javax.swing.JLabel();
        lblUnit2 = new javax.swing.JLabel();
        lblUnit1 = new javax.swing.JLabel();
        lblValueTotalAmount = new javax.swing.JLabel();
        lblValueDiscount = new javax.swing.JLabel();
        lblValueMustPay = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        lblOrderId = new javax.swing.JLabel();
        lblValueOrderId = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        jComboBoxValueEmployeeId = new javax.swing.JComboBox<>();
        lblEmployeeId = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        jComboBoxValueCustomerId = new javax.swing.JComboBox<>();
        lblCustomerName = new javax.swing.JLabel();
        lblValueCustomerName = new javax.swing.JLabel();
        lblOrderDate1 = new javax.swing.JLabel();
        jPanelOrderPay2 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        lblOrderId2 = new javax.swing.JLabel();
        lblValueOrderId2 = new javax.swing.JLabel();
        lblOrderDate2 = new javax.swing.JLabel();
        jComboBoxValueEmployeeId2 = new javax.swing.JComboBox<>();
        lblEmployeeId2 = new javax.swing.JLabel();
        lblCustomerName3 = new javax.swing.JLabel();
        jTextFieldValueCustomerMoneyGive1 = new javax.swing.JTextField();
        lblNote3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        lblOrderDate3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTotalAmount1 = new javax.swing.JLabel();
        lblDiscount1 = new javax.swing.JLabel();
        lblMustPay1 = new javax.swing.JLabel();
        lblUnit10 = new javax.swing.JLabel();
        lblUnit11 = new javax.swing.JLabel();
        lblUnit12 = new javax.swing.JLabel();
        lblValueTotalAmount1 = new javax.swing.JLabel();
        lblValueDiscount1 = new javax.swing.JLabel();
        lblValueMustPay1 = new javax.swing.JLabel();
        lblNote2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jpPay2 = new util.JPanelRounded();
        lblPay2 = new javax.swing.JLabel();
        svgPay2 = new util.SVGImage();
        pnlPay = new util.JPanelRounded();
        lblDeleteAll = new javax.swing.JLabel();
        svgDeleteAll = new util.SVGImage();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblValueProductPrice1 = new javax.swing.JLabel();
        lblProductPrice1 = new javax.swing.JLabel();
        lblProductQuantity1 = new javax.swing.JLabel();
        lblValueProductQuantity1 = new javax.swing.JLabel();
        lblValueProductName1 = new javax.swing.JLabel();
        jLabelProductImage1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblValueProductPrice2 = new javax.swing.JLabel();
        lblProductPrice2 = new javax.swing.JLabel();
        lblProductQuantity2 = new javax.swing.JLabel();
        lblValueProductQuantity2 = new javax.swing.JLabel();
        lblValueProductName2 = new javax.swing.JLabel();
        jLabelProductImage2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblValueProductPrice4 = new javax.swing.JLabel();
        lblProductPrice4 = new javax.swing.JLabel();
        lblProductQuantity4 = new javax.swing.JLabel();
        lblValueProductQuantity4 = new javax.swing.JLabel();
        lblValueProductName4 = new javax.swing.JLabel();
        jLabelProductImage4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblValueProductPrice3 = new javax.swing.JLabel();
        lblProductPrice3 = new javax.swing.JLabel();
        lblProductQuantity3 = new javax.swing.JLabel();
        lblValueProductQuantity3 = new javax.swing.JLabel();
        lblValueProductName3 = new javax.swing.JLabel();
        jLabelProductImage3 = new javax.swing.JLabel();
        jButtonRefresh5 = new javax.swing.JButton();
        lblSearchProduct1 = new javax.swing.JLabel();
        chkOrder = new javax.swing.JCheckBox();
        jpSearch = new util.JPanelRounded();
        lblSearch = new javax.swing.JLabel();
        svgSearch = new util.SVGImage();
        pnlDelete = new util.JPanelRounded();
        lblDelete = new javax.swing.JLabel();
        svgDelete = new util.SVGImage();
        pnlCreateInvoice = new util.JPanelRounded();
        lblCreateInvoice = new javax.swing.JLabel();
        svgCreateInvoice = new util.SVGImage();
        jp_reload = new util.JPanelRounded();
        svgReload = new util.SVGImage();

        setPreferredSize(new java.awt.Dimension(1040, 711));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelScanCode.setLayout(new java.awt.BorderLayout());
        add(jPanelScanCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 140));

        jPanelCart.setLayout(new java.awt.BorderLayout());

        tbl_Cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Cart);

        jPanelCart.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanelCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 700, 190));

        jTextFieldValueSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldValueSearchProduct.setText("8900767778797");
        jTextFieldValueSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueSearchProductActionPerformed(evt);
            }
        });
        add(jTextFieldValueSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, 30));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCategory.setText("Danh mục:");
        add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, 30));

        lblSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchProduct.setText("1/4");
        add(lblSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 710, 40, 30));

        jComboBoxValueCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueCategoryActionPerformed(evt);
            }
        });
        add(jComboBoxValueCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 140, 30));

        jButtonRefresh3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRefresh3.setText(">>");
        jButtonRefresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh3ActionPerformed(evt);
            }
        });
        add(jButtonRefresh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, 60, 30));

        jPanelOrderPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPay1.setBackground(new java.awt.Color(255, 255, 255));
        jpPay1.setRoundedBottomLeft(10);
        jpPay1.setRoundedBottomRight(10);
        jpPay1.setRoundedTopLeft(10);
        jpPay1.setRoundedTopRight(10);
        jpPay1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPay1MouseClicked(evt);
            }
        });
        jpPay1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPay1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPay1.setText("Thanh toán");
        jpPay1.add(lblPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 90, 40));

        svgPay1.setText(" ");
        jpPay1.add(svgPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 30, 30));

        jPanelOrderPay.add(jpPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 130, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalAmount.setText("Tổng tiền:");
        jPanel2.add(lblTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiscount.setText("Giảm giá:");
        jPanel2.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        lblMustPay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMustPay.setText("Phải trả:");
        jPanel2.add(lblMustPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        lblCustomerMoneyGive.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCustomerMoneyGive.setText("Tiền khách đưa:");
        jPanel2.add(lblCustomerMoneyGive, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        lblReturnMoneyToCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblReturnMoneyToCustomer.setText("Trả lại khách:");
        jPanel2.add(lblReturnMoneyToCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 30));

        jTextFieldValueCustomerMoneyGive.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldValueCustomerMoneyGive.setText("100.000.000");
        jTextFieldValueCustomerMoneyGive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueCustomerMoneyGiveActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldValueCustomerMoneyGive, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, 30));

        lblValueReturnMoneyToCustomer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueReturnMoneyToCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueReturnMoneyToCustomer.setText("100.000");
        jPanel2.add(lblValueReturnMoneyToCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 100, 30));

        lblUnit5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit5.setText("VNĐ");
        jPanel2.add(lblUnit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 30, 30));

        lblUnit4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit4.setText("VNĐ");
        jPanel2.add(lblUnit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 30, 30));

        lblUnit3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit3.setForeground(new java.awt.Color(255, 51, 51));
        lblUnit3.setText("VNĐ");
        jPanel2.add(lblUnit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 30, 30));

        lblUnit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit2.setText("VNĐ");
        jPanel2.add(lblUnit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 30, 30));

        lblUnit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit1.setText("VNĐ");
        jPanel2.add(lblUnit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 30, 30));

        lblValueTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueTotalAmount.setText("99.999.999");
        jPanel2.add(lblValueTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, 30));

        lblValueDiscount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueDiscount.setText("99.999");
        jPanel2.add(lblValueDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, 30));

        lblValueMustPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueMustPay.setForeground(new java.awt.Color(255, 51, 51));
        lblValueMustPay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueMustPay.setText("99.900.000");
        jPanel2.add(lblValueMustPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        lblNote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNote.setText("Ghi chú:");
        jPanel2.add(lblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, 100));

        jPanelOrderPay.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 340));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderId.setText("Mã đơn hàng:");
        jPanel4.add(lblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        lblValueOrderId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueOrderId.setText("HD001");
        jPanel4.add(lblValueOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, 30));

        lblOrderDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderDate.setText("01/01/2024 15:39 AM");
        jPanel4.add(lblOrderDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, 30));

        jComboBoxValueEmployeeId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueEmployeeIdActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxValueEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));

        lblEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmployeeId.setText("Mã nhân viên:");
        jPanel4.add(lblEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        lblCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCustomerId.setText("Mã khách hàng:");
        jPanel4.add(lblCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 30));

        jComboBoxValueCustomerId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueCustomerIdActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxValueCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 30));

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCustomerName.setText("Tên khách hàng:");
        jPanel4.add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        lblValueCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueCustomerName.setText("Nguyễn Văn A");
        jPanel4.add(lblValueCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 30));

        lblOrderDate1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderDate1.setText("Ngày tạo:");
        jPanel4.add(lblOrderDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        jPanelOrderPay.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 250));

        jTabbedPane2.addTab("Đơn hàng", jPanelOrderPay);

        jPanelOrderPay2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOrderId2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderId2.setText("Mã đơn hàng:");
        jPanel12.add(lblOrderId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        lblValueOrderId2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueOrderId2.setText("HD001");
        jPanel12.add(lblValueOrderId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, 30));

        lblOrderDate2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderDate2.setText("Ngày tạo:");
        jPanel12.add(lblOrderDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 30));

        jComboBoxValueEmployeeId2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueEmployeeId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueEmployeeId2ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBoxValueEmployeeId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 160, 30));

        lblEmployeeId2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmployeeId2.setText("Mã nhân viên:");
        jPanel12.add(lblEmployeeId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        lblCustomerName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCustomerName3.setText("Tên khách hàng:");
        jPanel12.add(lblCustomerName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jTextFieldValueCustomerMoneyGive1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldValueCustomerMoneyGive1.setText("Bành Văn A");
        jTextFieldValueCustomerMoneyGive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueCustomerMoneyGive1ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextFieldValueCustomerMoneyGive1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 160, 30));

        lblNote3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNote3.setText("Địa chỉ:");
        jPanel12.add(lblNote3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, 30));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 90));

        lblOrderDate3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOrderDate3.setText("01/01/2024 15:39 AM");
        jPanel12.add(lblOrderDate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 160, 30));

        jPanelOrderPay2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 280));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalAmount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalAmount1.setText("Tổng tiền:");
        jPanel3.add(lblTotalAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        lblDiscount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiscount1.setText("Giảm giá:");
        jPanel3.add(lblDiscount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        lblMustPay1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMustPay1.setText("Phải trả:");
        jPanel3.add(lblMustPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        lblUnit10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit10.setForeground(new java.awt.Color(255, 51, 51));
        lblUnit10.setText("VNĐ");
        jPanel3.add(lblUnit10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 30, 30));

        lblUnit11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit11.setText("VNĐ");
        jPanel3.add(lblUnit11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 30, 30));

        lblUnit12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUnit12.setText("VNĐ");
        jPanel3.add(lblUnit12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 30, 30));

        lblValueTotalAmount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueTotalAmount1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueTotalAmount1.setText("99.999.999");
        jPanel3.add(lblValueTotalAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, 30));

        lblValueDiscount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueDiscount1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueDiscount1.setText("99.999");
        jPanel3.add(lblValueDiscount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, 30));

        lblValueMustPay1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueMustPay1.setForeground(new java.awt.Color(255, 51, 51));
        lblValueMustPay1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueMustPay1.setText("99.900.000");
        jPanel3.add(lblValueMustPay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        lblNote2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNote2.setText("Ghi chú:");
        jPanel3.add(lblNote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 30));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 140, 100));

        jPanelOrderPay2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 300, 290));

        jpPay2.setBackground(new java.awt.Color(255, 255, 255));
        jpPay2.setRoundedBottomLeft(10);
        jpPay2.setRoundedBottomRight(10);
        jpPay2.setRoundedTopLeft(10);
        jpPay2.setRoundedTopRight(10);
        jpPay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPay2MouseClicked(evt);
            }
        });
        jpPay2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPay2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPay2.setText("Giao hàng");
        jpPay2.add(lblPay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 90, 40));

        svgPay2.setText(" ");
        jpPay2.add(svgPay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 30, 30));

        jPanelOrderPay2.add(jpPay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 130, 40));

        jTabbedPane2.addTab("Đặt hàng", jPanelOrderPay2);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 320, 720));

        pnlPay.setBackground(new java.awt.Color(255, 255, 255));
        pnlPay.setRoundedBottomLeft(10);
        pnlPay.setRoundedBottomRight(10);
        pnlPay.setRoundedTopLeft(10);
        pnlPay.setRoundedTopRight(10);
        pnlPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPayMouseClicked(evt);
            }
        });
        pnlPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDeleteAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDeleteAll.setText("Xóa tất cả");
        pnlPay.add(lblDeleteAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 30));

        svgDeleteAll.setText(" ");
        pnlPay.add(svgDeleteAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 20, 20));

        add(pnlPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 90, 30));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValueProductPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductPrice1.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductPrice1.setText("2.000.000");
        jPanel6.add(lblValueProductPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        lblProductPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductPrice1.setText("Giá:");
        jPanel6.add(lblProductPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 30));

        lblProductQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductQuantity1.setText("Số lượng:");
        jPanel6.add(lblProductQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 30));

        lblValueProductQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductQuantity1.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductQuantity1.setText("1.000");
        jPanel6.add(lblValueProductQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 30));

        lblValueProductName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductName1.setText("Đệ nhất kiếm tiền");
        jPanel6.add(lblValueProductName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 30));

        jLabelProductImage1.setText("Img");
        jPanel6.add(jLabelProductImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 150));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 250));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValueProductPrice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductPrice2.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductPrice2.setText("2.000.000");
        jPanel7.add(lblValueProductPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        lblProductPrice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductPrice2.setText("Giá:");
        jPanel7.add(lblProductPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 30));

        lblProductQuantity2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductQuantity2.setText("Số lượng:");
        jPanel7.add(lblProductQuantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 30));

        lblValueProductQuantity2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductQuantity2.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductQuantity2.setText("1.000");
        jPanel7.add(lblValueProductQuantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 30));

        lblValueProductName2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductName2.setText("Đệ nhất kiếm tiền");
        jPanel7.add(lblValueProductName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 30));

        jLabelProductImage2.setText("Img");
        jPanel7.add(jLabelProductImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 150));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 160, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValueProductPrice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductPrice4.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductPrice4.setText("2.000.000");
        jPanel9.add(lblValueProductPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        lblProductPrice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductPrice4.setText("Giá:");
        jPanel9.add(lblProductPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 30));

        lblProductQuantity4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductQuantity4.setText("Số lượng:");
        jPanel9.add(lblProductQuantity4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 30));

        lblValueProductQuantity4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductQuantity4.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductQuantity4.setText("1.000");
        jPanel9.add(lblValueProductQuantity4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 30));

        lblValueProductName4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductName4.setText("Đệ nhất kiếm tiền");
        jPanel9.add(lblValueProductName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 30));

        jLabelProductImage4.setText("Img");
        jPanel9.add(jLabelProductImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 150));

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 160, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValueProductPrice3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductPrice3.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductPrice3.setText("2.000.000");
        jPanel8.add(lblValueProductPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        lblProductPrice3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductPrice3.setText("Giá:");
        jPanel8.add(lblProductPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 30));

        lblProductQuantity3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProductQuantity3.setText("Số lượng:");
        jPanel8.add(lblProductQuantity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 30));

        lblValueProductQuantity3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValueProductQuantity3.setForeground(new java.awt.Color(255, 51, 51));
        lblValueProductQuantity3.setText("1.000");
        jPanel8.add(lblValueProductQuantity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 50, 30));

        lblValueProductName3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductName3.setText("Đệ nhất kiếm tiền");
        jPanel8.add(lblValueProductName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 30));

        jLabelProductImage3.setText("Img");
        jPanel8.add(jLabelProductImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 150));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 160, -1));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 700, 280));

        jButtonRefresh5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonRefresh5.setText("<<");
        jButtonRefresh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh5ActionPerformed(evt);
            }
        });
        add(jButtonRefresh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 710, 60, 30));

        lblSearchProduct1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearchProduct1.setText("Tìm kiếm sản phẩm:");
        add(lblSearchProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        chkOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chkOrder.setText("Đặt hàng");
        chkOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOrderActionPerformed(evt);
            }
        });
        add(chkOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, 30));

        jpSearch.setBackground(new java.awt.Color(255, 255, 255));
        jpSearch.setRoundedBottomLeft(10);
        jpSearch.setRoundedBottomRight(10);
        jpSearch.setRoundedTopLeft(10);
        jpSearch.setRoundedTopRight(10);
        jpSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpSearchMouseClicked(evt);
            }
        });
        jpSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSearch.setText("Tìm");
        jpSearch.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        svgSearch.setText(" ");
        jpSearch.add(svgSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 20, 20));

        add(jpSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, 30));

        pnlDelete.setBackground(new java.awt.Color(255, 255, 255));
        pnlDelete.setRoundedBottomLeft(10);
        pnlDelete.setRoundedBottomRight(10);
        pnlDelete.setRoundedTopLeft(10);
        pnlDelete.setRoundedTopRight(10);
        pnlDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDeleteMouseClicked(evt);
            }
        });
        pnlDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDelete.setText("Xóa");
        pnlDelete.add(lblDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 30, 30));

        svgDelete.setText(" ");
        pnlDelete.add(svgDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 20, 20));

        add(pnlDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 30));

        pnlCreateInvoice.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreateInvoice.setRoundedBottomLeft(10);
        pnlCreateInvoice.setRoundedBottomRight(10);
        pnlCreateInvoice.setRoundedTopLeft(10);
        pnlCreateInvoice.setRoundedTopRight(10);
        pnlCreateInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCreateInvoiceMouseClicked(evt);
            }
        });
        pnlCreateInvoice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateInvoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCreateInvoice.setText("Tạo hóa đơn");
        pnlCreateInvoice.add(lblCreateInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 70, 30));

        svgCreateInvoice.setText(" ");
        pnlCreateInvoice.add(svgCreateInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 20, 20));

        add(pnlCreateInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 110, 30));

        jp_reload.setBackground(new java.awt.Color(255, 255, 255));
        jp_reload.setRoundedBottomLeft(10);
        jp_reload.setRoundedBottomRight(10);
        jp_reload.setRoundedTopLeft(10);
        jp_reload.setRoundedTopRight(10);
        jp_reload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp_reloadMouseClicked(evt);
            }
        });
        jp_reload.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        svgReload.setText(" ");
        jp_reload.add(svgReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 20, 20));

        add(jp_reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 710, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxValueEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueEmployeeIdActionPerformed

    private void jComboBoxValueCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueCustomerIdActionPerformed

    private void jTextFieldValueCustomerMoneyGiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueCustomerMoneyGiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueCustomerMoneyGiveActionPerformed

    private void jTextFieldValueSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueSearchProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueSearchProductActionPerformed

    private void jComboBoxValueCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueCategoryActionPerformed

    private void jButtonRefresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefresh3ActionPerformed

    private void pnlPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPayMouseClicked

    }//GEN-LAST:event_pnlPayMouseClicked

    private void jpPay1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPay1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpPay1MouseClicked

    private void jButtonRefresh5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefresh5ActionPerformed

    private void jComboBoxValueEmployeeId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueEmployeeId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueEmployeeId2ActionPerformed

    private void jTextFieldValueCustomerMoneyGive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueCustomerMoneyGive1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueCustomerMoneyGive1ActionPerformed

    private void jpPay2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPay2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpPay2MouseClicked

    private void chkOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOrderActionPerformed

    private void jpSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jpSearchMouseClicked

    private void pnlDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDeleteMouseClicked

    private void pnlCreateInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreateInvoiceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlCreateInvoiceMouseClicked

    private void jp_reloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp_reloadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_reloadMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkOrder;
    private javax.swing.JButton jButtonRefresh3;
    private javax.swing.JButton jButtonRefresh5;
    private javax.swing.JComboBox<String> jComboBoxValueCategory;
    private javax.swing.JComboBox<String> jComboBoxValueCustomerId;
    private javax.swing.JComboBox<String> jComboBoxValueEmployeeId;
    private javax.swing.JComboBox<String> jComboBoxValueEmployeeId2;
    private javax.swing.JLabel jLabelProductImage1;
    private javax.swing.JLabel jLabelProductImage2;
    private javax.swing.JLabel jLabelProductImage3;
    private javax.swing.JLabel jLabelProductImage4;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelCart;
    private javax.swing.JPanel jPanelOrderPay;
    private javax.swing.JPanel jPanelOrderPay2;
    private javax.swing.JPanel jPanelScanCode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextFieldValueCustomerMoneyGive;
    private javax.swing.JTextField jTextFieldValueCustomerMoneyGive1;
    private javax.swing.JTextField jTextFieldValueSearchProduct;
    private util.JPanelRounded jpPay1;
    private util.JPanelRounded jpPay2;
    private util.JPanelRounded jpSearch;
    private util.JPanelRounded jp_reload;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCreateInvoice;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerMoneyGive;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblCustomerName3;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblDeleteAll;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscount1;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblEmployeeId2;
    private javax.swing.JLabel lblMustPay;
    private javax.swing.JLabel lblMustPay1;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblNote2;
    private javax.swing.JLabel lblNote3;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderDate1;
    private javax.swing.JLabel lblOrderDate2;
    private javax.swing.JLabel lblOrderDate3;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblOrderId2;
    private javax.swing.JLabel lblPay1;
    private javax.swing.JLabel lblPay2;
    private javax.swing.JLabel lblProductPrice1;
    private javax.swing.JLabel lblProductPrice2;
    private javax.swing.JLabel lblProductPrice3;
    private javax.swing.JLabel lblProductPrice4;
    private javax.swing.JLabel lblProductQuantity1;
    private javax.swing.JLabel lblProductQuantity2;
    private javax.swing.JLabel lblProductQuantity3;
    private javax.swing.JLabel lblProductQuantity4;
    private javax.swing.JLabel lblReturnMoneyToCustomer;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchProduct;
    private javax.swing.JLabel lblSearchProduct1;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblTotalAmount1;
    private javax.swing.JLabel lblUnit1;
    private javax.swing.JLabel lblUnit10;
    private javax.swing.JLabel lblUnit11;
    private javax.swing.JLabel lblUnit12;
    private javax.swing.JLabel lblUnit2;
    private javax.swing.JLabel lblUnit3;
    private javax.swing.JLabel lblUnit4;
    private javax.swing.JLabel lblUnit5;
    private javax.swing.JLabel lblValueCustomerName;
    private javax.swing.JLabel lblValueDiscount;
    private javax.swing.JLabel lblValueDiscount1;
    private javax.swing.JLabel lblValueMustPay;
    private javax.swing.JLabel lblValueMustPay1;
    private javax.swing.JLabel lblValueOrderId;
    private javax.swing.JLabel lblValueOrderId2;
    private javax.swing.JLabel lblValueProductName1;
    private javax.swing.JLabel lblValueProductName2;
    private javax.swing.JLabel lblValueProductName3;
    private javax.swing.JLabel lblValueProductName4;
    private javax.swing.JLabel lblValueProductPrice1;
    private javax.swing.JLabel lblValueProductPrice2;
    private javax.swing.JLabel lblValueProductPrice3;
    private javax.swing.JLabel lblValueProductPrice4;
    private javax.swing.JLabel lblValueProductQuantity1;
    private javax.swing.JLabel lblValueProductQuantity2;
    private javax.swing.JLabel lblValueProductQuantity3;
    private javax.swing.JLabel lblValueProductQuantity4;
    private javax.swing.JLabel lblValueReturnMoneyToCustomer;
    private javax.swing.JLabel lblValueTotalAmount;
    private javax.swing.JLabel lblValueTotalAmount1;
    private util.JPanelRounded pnlCreateInvoice;
    private util.JPanelRounded pnlDelete;
    private util.JPanelRounded pnlPay;
    private util.SVGImage svgCreateInvoice;
    private util.SVGImage svgDelete;
    private util.SVGImage svgDeleteAll;
    private util.SVGImage svgPay1;
    private util.SVGImage svgPay2;
    private util.SVGImage svgReload;
    private util.SVGImage svgSearch;
    private javax.swing.JTable tbl_Cart;
    // End of variables declaration//GEN-END:variables
}