/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ButtonGroup;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VONG VINH LOI
 */
public class jpannelEmployee extends javax.swing.JPanel {

    private ButtonGroup btgroup;
    private DefaultTableModel modelNhanVien;

    public jpannelEmployee() {
        modelNhanVien = new DefaultTableModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHead = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbMaNV = new javax.swing.JLabel();
        jcbMaNV = new javax.swing.JComboBox<>();
        jbHoTen = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jbGioiTinh = new javax.swing.JLabel();
        btgroup = new ButtonGroup();
        radNu = new javax.swing.JRadioButton();
        radNam = new javax.swing.JRadioButton();
        jbSoDienThoai = new javax.swing.JLabel();
        jcbTrangThai = new javax.swing.JComboBox<>();
        jbTrangThai = new javax.swing.JLabel();
        jbDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jcbChucVu = new javax.swing.JComboBox<>();
        jbChucVu = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jbDiaChi1 = new javax.swing.JLabel();
        jdNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelNhanVien = new DefaultTableModel();
        tableEmployee = new JTable(modelNhanVien);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 760));
        setLayout(new java.awt.BorderLayout());

        jpHead.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("QUẢN LÝ NHÂN VIÊN");
        jLabel11.setPreferredSize(new java.awt.Dimension(349, 50));
        jpHead.add(jLabel11, java.awt.BorderLayout.CENTER);

        add(jpHead, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaNV.setText("Mã nhân viên:");
        jPanel2.add(lbMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        jcbMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbMaNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcbMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, 30));

        jbHoTen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbHoTen.setText("Họ Và Tên:");
        jPanel2.add(jbHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 180, 30));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 100, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, 30));

        jbGioiTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbGioiTinh.setText("Giới tính:");
        jPanel2.add(jbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, 30));

        btgroup.add(radNam);
        btgroup.add(radNu);
        radNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radNu.setText("Nữ");
        radNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNuActionPerformed(evt);
            }
        });
        jPanel2.add(radNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, 30));

        radNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radNam.setSelected(true);
        radNam.setText("Nam");
        radNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNamActionPerformed(evt);
            }
        });
        jPanel2.add(radNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, -1, 30));

        jbSoDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSoDienThoai.setText("Số điện thoại:");
        jPanel2.add(jbSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, 30));

        jcbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lí"}));
        jPanel2.add(jcbTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 180, 30));

        jbTrangThai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbTrangThai.setText("Trạng thái:");
        jPanel2.add(jbTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 30));

        jbDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDiaChi.setText("Ngày sinh:");
        jPanel2.add(jbDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 30));

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 290, 30));

        jcbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jcbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, 30));

        jbChucVu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbChucVu.setText("Chức vụ:");
        jPanel2.add(jbChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });
        jPanel2.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, 30));

        jbDiaChi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDiaChi1.setText("Địa chỉ:");
        jPanel2.add(jbDiaChi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 30));

        jdNgaySinh.setDateFormatString("dd MM yyyy");
        jPanel2.add(jdNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 290, 30));

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 480));

        modelNhanVien.addColumn("Ma nhân viên");
        modelNhanVien.addColumn("Tên nhân viên");
        modelNhanVien.addColumn("Chức vụ");
        modelNhanVien.addColumn("Trạng Thái");
        modelNhanVien.addColumn("Địa Chỉ");
        modelNhanVien.addColumn("Số điện thoại");
        modelNhanVien.addColumn("Giới tính");
        modelNhanVien.addColumn("Ngày sinh");
        tableEmployee.setBorder(new com.formdev.flatlaf.ui.FlatBorder());
        tableEmployee.setModel(modelNhanVien);
        jScrollPane1.setViewportView(tableEmployee);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void radNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNuActionPerformed

    private void radNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNamActionPerformed

    private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoTenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbChucVu;
    private javax.swing.JLabel jbDiaChi;
    private javax.swing.JLabel jbDiaChi1;
    private javax.swing.JLabel jbGioiTinh;
    private javax.swing.JLabel jbHoTen;
    private javax.swing.JLabel jbSoDienThoai;
    private javax.swing.JLabel jbTrangThai;
    private javax.swing.JComboBox<String> jcbChucVu;
    private javax.swing.JComboBox<String> jcbMaNV;
    private javax.swing.JComboBox<String> jcbTrangThai;
    private com.toedter.calendar.JDateChooser jdNgaySinh;
    private javax.swing.JPanel jpHead;
    private javax.swing.JLabel lbMaNV;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
