/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author BanhMi88
 */
public class JPanel_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_ThongKe
     */
    public JPanel_ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTab = new javax.swing.JTabbedPane();
        tabDoanhThu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledoanhthu = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        ngayketthuc = new com.toedter.calendar.JDateChooser();
        ngaybatdau = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdoanhthu = new javax.swing.JLabel();
        txtsoluonghoadon = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tabNhanVien = new javax.swing.JPanel();
        tabKhachHang1 = new javax.swing.JPanel();
        panelFunction1 = new javax.swing.JPanel();
        ngayketthuc2 = new com.toedter.calendar.JDateChooser();
        ngaybatdau2 = new com.toedter.calendar.JDateChooser();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtdoanhthu2 = new javax.swing.JLabel();
        txtsoluonghoadon2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabKhachHang = new javax.swing.JPanel();
        panelFunction = new javax.swing.JPanel();
        ngayketthuc1 = new com.toedter.calendar.JDateChooser();
        ngaybatdau1 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdoanhthu1 = new javax.swing.JLabel();
        txtsoluonghoadon1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        scrollThongKe = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1040, 760));
        setLayout(new java.awt.BorderLayout());

        jTab.setPreferredSize(new java.awt.Dimension(100, 760));

        tabDoanhThu.setPreferredSize(new java.awt.Dimension(1061, 760));
        tabDoanhThu.setLayout(new java.awt.BorderLayout());

        tabledoanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Tên nhân viên", "Ngày tạo", "Tổng thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabledoanhthu);

        tabDoanhThu.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(ngayketthuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, 30));
        jPanel4.add(ngaybatdau, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 180, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("---------------------------------");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("In thống kê");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Xem thống kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Đến ngày:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Đến ngày:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Doanh thu:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 100, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tổng doanh thu");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Số lượng hóa đơn bán được:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 240, -1));

        txtdoanhthu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(txtdoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 30));

        txtsoluonghoadon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel4.add(txtsoluonghoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Từ ngày:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        jButton3.setText("Biểu đồ tổng quát");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 140, 50));

        tabDoanhThu.add(jPanel4, java.awt.BorderLayout.WEST);

        jTab.addTab("Doanh Thu", tabDoanhThu);

        tabKhachHang1.setLayout(new java.awt.BorderLayout());

        panelFunction1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFunction1.add(ngayketthuc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, 30));
        panelFunction1.add(ngaybatdau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 180, 30));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("In thống kê");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelFunction1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Xem thống kê");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelFunction1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Đến ngày:");
        panelFunction1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Đến ngày:");
        panelFunction1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        txtdoanhthu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelFunction1.add(txtdoanhthu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 30));

        txtsoluonghoadon2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelFunction1.add(txtsoluonghoadon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 30, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Từ ngày:");
        panelFunction1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        jButton9.setText("Biểu đồ tổng quát");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelFunction1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, 50));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sản phẩm đã bán", "Sản phẩm được bán nhiều nhất", "Sản phẩm được bán ít nhấtt", "Sản phẩm có doanh thu cao nhất", "Sản phẩm tồn kho nhiều nhất", "Sản phẩm tồn kho ít nhất" }));
        panelFunction1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 200, 30));

        tabKhachHang1.add(panelFunction1, java.awt.BorderLayout.WEST);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        tabKhachHang1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout tabNhanVienLayout = new javax.swing.GroupLayout(tabNhanVien);
        tabNhanVien.setLayout(tabNhanVienLayout);
        tabNhanVienLayout.setHorizontalGroup(
            tabNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(tabNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabNhanVienLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tabNhanVienLayout.setVerticalGroup(
            tabNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(tabNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabNhanVienLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTab.addTab("Sản Phẩm", tabNhanVien);

        tabKhachHang.setLayout(new java.awt.BorderLayout());

        panelFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFunction.add(ngayketthuc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 180, 30));
        panelFunction.add(ngaybatdau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 180, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("In thống kê");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelFunction.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Xem thống kê");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelFunction.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Đến ngày:");
        panelFunction.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Đến ngày:");
        panelFunction.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        txtdoanhthu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelFunction.add(txtdoanhthu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 30));

        txtsoluonghoadon1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelFunction.add(txtsoluonghoadon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Từ ngày:");
        panelFunction.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        jButton6.setText("Biểu đồ tổng quát");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelFunction.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, 50));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng đã mua hàng", "Khách hàng tổng chi cao nhất", "Khách hàng tổng chi thấp nhất", "Khách hàng mới đăng ký", "Khách hàng mua hàng nhiều nhất", "Khách hàng mua hàng ít nhất", " " }));
        panelFunction.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 180, 30));

        tabKhachHang.add(panelFunction, java.awt.BorderLayout.WEST);

        tableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ", "Giới tính", "Số lượng", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollThongKe.setViewportView(tableThongKe);

        tabKhachHang.add(scrollThongKe, java.awt.BorderLayout.CENTER);

        jTab.addTab("Khách hàng", tabKhachHang);

        add(jTab, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser ngaybatdau;
    private com.toedter.calendar.JDateChooser ngaybatdau1;
    private com.toedter.calendar.JDateChooser ngaybatdau2;
    private com.toedter.calendar.JDateChooser ngayketthuc;
    private com.toedter.calendar.JDateChooser ngayketthuc1;
    private com.toedter.calendar.JDateChooser ngayketthuc2;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JPanel panelFunction1;
    private javax.swing.JScrollPane scrollThongKe;
    private javax.swing.JPanel tabDoanhThu;
    private javax.swing.JPanel tabKhachHang;
    private javax.swing.JPanel tabKhachHang1;
    private javax.swing.JPanel tabNhanVien;
    private javax.swing.JTable tableThongKe;
    private javax.swing.JTable tabledoanhthu;
    private javax.swing.JLabel txtdoanhthu;
    private javax.swing.JLabel txtdoanhthu1;
    private javax.swing.JLabel txtdoanhthu2;
    private javax.swing.JLabel txtsoluonghoadon;
    private javax.swing.JLabel txtsoluonghoadon1;
    private javax.swing.JLabel txtsoluonghoadon2;
    // End of variables declaration//GEN-END:variables
}
