/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.PlanarYUVLuminanceSource;
import com.google.zxing.Reader;
import com.google.zxing.Result;
import com.google.zxing.common.HybridBinarizer;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;

/**
 *
 * @author pc
 */
public class JPanelSell extends javax.swing.JPanel {

    /**
     * Creates new form JPanelSell
     */
    public JPanelSell() {
        initComponents();
        Thread thread = new Thread(
                () -> scanCode()
        );
        thread.start();
       
    }

    public void scanCode() {
        Webcam webcam = Webcam.getDefault();
        webcam.open();

        WebcamPanel webcamPanel = new WebcamPanel(webcam);
        webcamPanel.setFPSDisplayed(true);
        webcamPanel.setDisplayDebugInfo(true);
        webcamPanel.setImageSizeDisplayed(true);
        webcamPanel.setMirrored(false); // Đừng đảo ngược hình ảnh

        jPanelScanCode.add(webcamPanel, BorderLayout.CENTER);
        jPanelScanCode.repaint();
        jPanelScanCode.revalidate();
        while (true) {
            BufferedImage image = webcam.getImage();
            Result result = decodeBarcode(image);
            if (result != null) {
                jTextFieldValueSearchProduct.setText(result.getText());
            }
        }
    }

    private static Result decodeBarcode(BufferedImage image) {
        try {
            int width = image.getWidth();
            int height = image.getHeight();
            int[] pixels = new int[width * height];
            image.getRGB(0, 0, width, height, pixels, 0, width);

            LuminanceSource source = new PlanarYUVLuminanceSource(
                    toByteArray(pixels, width, height),
                    width,
                    height,
                    0,
                    0,
                    width,
                    height,
                    false
            );

            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            Reader reader = new MultiFormatReader();
            return reader.decode(bitmap);
        } catch (NotFoundException e) {
            // Không tìm thấy mã vạch
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private static byte[] toByteArray(int[] pixels, int width, int height) {
        byte[] byteArray = new byte[width * height];
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                int pixel = pixels[i * width + j];
                byteArray[i * width + j] = (byte) ((pixel >> 16) & 0xFF);
            }
        }
        return byteArray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_orderInfomation = new javax.swing.JPanel();
        lblValueOrderId = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        lblEmployeeId = new javax.swing.JLabel();
        jComboBoxValueEmployeeId = new javax.swing.JComboBox<>();
        lblCustomerId = new javax.swing.JLabel();
        jComboBoxValueCustomerId = new javax.swing.JComboBox<>();
        lblOrderDate = new javax.swing.JLabel();
        jDateChooserValueOrderDate = new com.toedter.calendar.JDateChooser();
        lblCustomerName = new javax.swing.JLabel();
        lblValueCustomerName = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        jTextFieldValueNote = new javax.swing.JTextField();
        jPanelScanCode = new javax.swing.JPanel();
        jPanelCart = new javax.swing.JPanel();
        jScrollPaneCart = new javax.swing.JScrollPane();
        jTableCart = new javax.swing.JTable();
        jPanelOrderPay = new javax.swing.JPanel();
        lblTotalAmount = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblValueDiscount = new javax.swing.JLabel();
        lblMustPay = new javax.swing.JLabel();
        lblUnit5 = new javax.swing.JLabel();
        lblReturnMoneyToCustomer = new javax.swing.JLabel();
        lblValueReturnMoneyToCustomer = new javax.swing.JLabel();
        lblCustomerMoneyGive = new javax.swing.JLabel();
        jTextFieldValueCustomerMoneyGive = new javax.swing.JTextField();
        lblValueMustPay = new javax.swing.JLabel();
        lblUnit2 = new javax.swing.JLabel();
        lblUnit3 = new javax.swing.JLabel();
        lblUnit4 = new javax.swing.JLabel();
        lblValueTotalAmount = new javax.swing.JLabel();
        lblUnit1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonCancel2 = new javax.swing.JButton();
        jButtonRefresh2 = new javax.swing.JButton();
        panelListProduct = new javax.swing.JPanel();
        jScrollPaneListProduct = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelProductItem = new javax.swing.JPanel();
        jLabelProductImage = new javax.swing.JLabel();
        lblValueProductId = new javax.swing.JLabel();
        lblProductId = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblValueProductName = new javax.swing.JLabel();
        lblProductQuantity = new javax.swing.JLabel();
        lblValueProductQuantity = new javax.swing.JLabel();
        lblUnit6 = new javax.swing.JLabel();
        lblValueProductPrice = new javax.swing.JLabel();
        jButtonRefresh1 = new javax.swing.JButton();
        lblAuthor = new javax.swing.JLabel();
        lblVAlueAuthor = new javax.swing.JLabel();
        lblProductPrice = new javax.swing.JLabel();
        jPanelProductItem1 = new javax.swing.JPanel();
        jLabelProductImage1 = new javax.swing.JLabel();
        lblValueProductId1 = new javax.swing.JLabel();
        lblProductId1 = new javax.swing.JLabel();
        lblProductName1 = new javax.swing.JLabel();
        lblValueProductName1 = new javax.swing.JLabel();
        lblProductQuantity1 = new javax.swing.JLabel();
        lblValueProductQuantity1 = new javax.swing.JLabel();
        lblUnit7 = new javax.swing.JLabel();
        lblValueProductPrice1 = new javax.swing.JLabel();
        jButtonRefresh4 = new javax.swing.JButton();
        lblAuthor1 = new javax.swing.JLabel();
        lblVAlueAuthor1 = new javax.swing.JLabel();
        lblProductPrice1 = new javax.swing.JLabel();
        jTextFieldValueSearchProduct = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        jButtonCancel1 = new javax.swing.JButton();
        lblSearchProduct = new javax.swing.JLabel();
        jButtonCancel3 = new javax.swing.JButton();
        jComboBoxValueCategory = new javax.swing.JComboBox<>();
        jButtonRefresh3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1040, 711));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValueOrderId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueOrderId.setText("HD001");

        lblOrderId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderId.setText("Mã đơn hàng:");

        lblEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmployeeId.setText("Mã nhân viên:");

        jComboBoxValueEmployeeId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueEmployeeIdActionPerformed(evt);
            }
        });

        lblCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerId.setText("Mã khách hàng:");

        jComboBoxValueCustomerId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueCustomerIdActionPerformed(evt);
            }
        });

        lblOrderDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrderDate.setText("Ngày tạo:");

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerName.setText("Tên khách hàng:");

        lblValueCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueCustomerName.setText("Nguyễn Văn A");

        lblNote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNote.setText("Ghi chú:");

        jTextFieldValueNote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldValueNote.setText("Khách vip");
        jTextFieldValueNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueNoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_orderInfomationLayout = new javax.swing.GroupLayout(jPanel_orderInfomation);
        jPanel_orderInfomation.setLayout(jPanel_orderInfomationLayout);
        jPanel_orderInfomationLayout.setHorizontalGroup(
            jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                        .addComponent(lblEmployeeId)
                        .addGap(15, 15, 15)
                        .addComponent(jComboBoxValueEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrderId)
                            .addComponent(lblOrderDate))
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblValueOrderId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooserValueOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomerName)
                    .addComponent(lblCustomerId)
                    .addComponent(lblNote))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxValueCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jTextFieldValueNote))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_orderInfomationLayout.setVerticalGroup(
            jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxValueCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValueCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldValueNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValueOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_orderInfomationLayout.createSequentialGroup()
                                .addComponent(jComboBoxValueEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_orderInfomationLayout.createSequentialGroup()
                                .addComponent(lblEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_orderInfomationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(lblOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDateChooserValueOrderDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel_orderInfomation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 150));

        jPanelScanCode.setLayout(new java.awt.BorderLayout());
        add(jPanelScanCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 270, 140));

        jPanelCart.setLayout(new java.awt.BorderLayout());

        jTableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneCart.setViewportView(jTableCart);

        jPanelCart.add(jScrollPaneCart, java.awt.BorderLayout.CENTER);

        add(jPanelCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1040, 180));

        jPanelOrderPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalAmount.setText("Tổng tiền:");
        jPanelOrderPay.add(lblTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiscount.setText("Giảm giá:");
        jPanelOrderPay.add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        lblValueDiscount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueDiscount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueDiscount.setText("99.999");
        jPanelOrderPay.add(lblValueDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 50, 100, 30));

        lblMustPay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMustPay.setText("Phải trả:");
        jPanelOrderPay.add(lblMustPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        lblUnit5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit5.setText("VNĐ");
        jPanelOrderPay.add(lblUnit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 40, 30));

        lblReturnMoneyToCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblReturnMoneyToCustomer.setText("Trả lại khách:");
        jPanelOrderPay.add(lblReturnMoneyToCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        lblValueReturnMoneyToCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueReturnMoneyToCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueReturnMoneyToCustomer.setText("100.000");
        jPanelOrderPay.add(lblValueReturnMoneyToCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 30));

        lblCustomerMoneyGive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCustomerMoneyGive.setText("Tiền khách đưa:");
        jPanelOrderPay.add(lblCustomerMoneyGive, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        jTextFieldValueCustomerMoneyGive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldValueCustomerMoneyGive.setText("100.000.000");
        jTextFieldValueCustomerMoneyGive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueCustomerMoneyGiveActionPerformed(evt);
            }
        });
        jPanelOrderPay.add(jTextFieldValueCustomerMoneyGive, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 30));

        lblValueMustPay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValueMustPay.setForeground(new java.awt.Color(255, 51, 51));
        lblValueMustPay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueMustPay.setText("99.900.000");
        jPanelOrderPay.add(lblValueMustPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 90, 100, 30));

        lblUnit2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit2.setText("VNĐ");
        jPanelOrderPay.add(lblUnit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 40, 30));

        lblUnit3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit3.setText("VNĐ");
        jPanelOrderPay.add(lblUnit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 40, 30));

        lblUnit4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit4.setText("VNĐ");
        jPanelOrderPay.add(lblUnit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 40, 30));

        lblValueTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueTotalAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValueTotalAmount.setText("99.999.999");
        jPanelOrderPay.add(lblValueTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 30));

        lblUnit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit1.setText("VNĐ");
        jPanelOrderPay.add(lblUnit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Thanh toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelOrderPay.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 130, 40));

        jButtonCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancel.setText("Hủy đơn");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelOrderPay.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButtonRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRefresh.setText("Làm mới");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        jPanelOrderPay.add(jButtonRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jButtonCancel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancel2.setText("Hủy đơn");
        jButtonCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel2ActionPerformed(evt);
            }
        });
        jPanelOrderPay.add(jButtonCancel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jButtonRefresh2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRefresh2.setText("Làm mới");
        jButtonRefresh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh2ActionPerformed(evt);
            }
        });
        jPanelOrderPay.add(jButtonRefresh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        add(jPanelOrderPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 280, 350));

        jPanelProductItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProductImage.setText("Img");
        jPanelProductItem.add(jLabelProductImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 241));

        lblValueProductId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductId.setText("8900767778797");
        jPanelProductItem.add(lblValueProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 30));

        lblProductId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductId.setText("Mã sản phẩm:");
        jPanelProductItem.add(lblProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 30));

        lblProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductName.setText("Tên sản phẩm:");
        jPanelProductItem.add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 30));

        lblValueProductName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductName.setText("Đệ nhất kiếm tiền");
        jPanelProductItem.add(lblValueProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 160, 30));

        lblProductQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductQuantity.setText("Số lượng");
        jPanelProductItem.add(lblProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 30));

        lblValueProductQuantity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductQuantity.setText("1.000");
        jPanelProductItem.add(lblValueProductQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 120, 30));

        lblUnit6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit6.setText("VNĐ");
        jPanelProductItem.add(lblUnit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 30));

        lblValueProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductPrice.setText("199.000");
        jPanelProductItem.add(lblValueProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, 30));

        jButtonRefresh1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRefresh1.setText("Thêm");
        jButtonRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh1ActionPerformed(evt);
            }
        });
        jPanelProductItem.add(jButtonRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 80, 30));

        lblAuthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAuthor.setText("Tác giả:");
        jPanelProductItem.add(lblAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 30));

        lblVAlueAuthor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVAlueAuthor.setText("Huấn Rose");
        jPanelProductItem.add(lblVAlueAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 160, 30));

        lblProductPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductPrice.setText("Giá:");
        jPanelProductItem.add(lblProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));

        jPanelProductItem1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelProductImage1.setText("Img");
        jPanelProductItem1.add(jLabelProductImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 241));

        lblValueProductId1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductId1.setText("8900767778797");
        jPanelProductItem1.add(lblValueProductId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 30));

        lblProductId1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductId1.setText("Mã sản phẩm:");
        jPanelProductItem1.add(lblProductId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 30));

        lblProductName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductName1.setText("Tên sản phẩm:");
        jPanelProductItem1.add(lblProductName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, 30));

        lblValueProductName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductName1.setText("Đệ nhất kiếm tiền");
        jPanelProductItem1.add(lblValueProductName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 160, 30));

        lblProductQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductQuantity1.setText("Số lượng");
        jPanelProductItem1.add(lblProductQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, 30));

        lblValueProductQuantity1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductQuantity1.setText("1.000");
        jPanelProductItem1.add(lblValueProductQuantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 120, 30));

        lblUnit7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnit7.setText("VNĐ");
        jPanelProductItem1.add(lblUnit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 30));

        lblValueProductPrice1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValueProductPrice1.setText("199.000");
        jPanelProductItem1.add(lblValueProductPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, 30));

        jButtonRefresh4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRefresh4.setText("Thêm");
        jButtonRefresh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh4ActionPerformed(evt);
            }
        });
        jPanelProductItem1.add(jButtonRefresh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 80, 30));

        lblAuthor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAuthor1.setText("Tác giả:");
        jPanelProductItem1.add(lblAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 30));

        lblVAlueAuthor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVAlueAuthor1.setText("Huấn Rose");
        jPanelProductItem1.add(lblVAlueAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 160, 30));

        lblProductPrice1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductPrice1.setText("Giá:");
        jPanelProductItem1.add(lblProductPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelProductItem, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelProductItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelProductItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelProductItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jScrollPaneListProduct.setViewportView(jPanel1);

        javax.swing.GroupLayout panelListProductLayout = new javax.swing.GroupLayout(panelListProduct);
        panelListProduct.setLayout(panelListProductLayout);
        panelListProductLayout.setHorizontalGroup(
            panelListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneListProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        panelListProductLayout.setVerticalGroup(
            panelListProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListProductLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPaneListProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );

        add(panelListProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 730, 260));

        jTextFieldValueSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldValueSearchProduct.setText("8900767778797");
        jTextFieldValueSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValueSearchProductActionPerformed(evt);
            }
        });
        add(jTextFieldValueSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 170, 30));

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategory.setText("Danh mục:");
        add(lblCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, 30));

        jButtonCancel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancel1.setText("Xóa tất cả");
        jButtonCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel1ActionPerformed(evt);
            }
        });
        add(jButtonCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 110, 30));

        lblSearchProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSearchProduct.setText("Tìm kiếm sản phẩm:");
        add(lblSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 30));

        jButtonCancel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCancel3.setText("Tìm");
        jButtonCancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancel3ActionPerformed(evt);
            }
        });
        add(jButtonCancel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, 30));

        jComboBoxValueCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxValueCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValueCategoryActionPerformed(evt);
            }
        });
        add(jComboBoxValueCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 158, 30));

        jButtonRefresh3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRefresh3.setText("Xóa");
        jButtonRefresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefresh3ActionPerformed(evt);
            }
        });
        add(jButtonRefresh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxValueEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueEmployeeIdActionPerformed

    private void jComboBoxValueCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueCustomerIdActionPerformed

    private void jTextFieldValueCustomerMoneyGiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueCustomerMoneyGiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueCustomerMoneyGiveActionPerformed

    private void jTextFieldValueNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueNoteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jTextFieldValueSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValueSearchProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValueSearchProductActionPerformed

    private void jButtonCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancel2ActionPerformed

    private void jButtonRefresh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefresh2ActionPerformed

    private void jButtonCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancel1ActionPerformed

    private void jButtonCancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancel3ActionPerformed

    private void jComboBoxValueCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValueCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxValueCategoryActionPerformed

    private void jButtonRefresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefresh3ActionPerformed

    private void jButtonRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefresh1ActionPerformed

    private void jButtonRefresh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefresh4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRefresh4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonCancel2;
    private javax.swing.JButton jButtonCancel3;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefresh1;
    private javax.swing.JButton jButtonRefresh2;
    private javax.swing.JButton jButtonRefresh3;
    private javax.swing.JButton jButtonRefresh4;
    private javax.swing.JComboBox<String> jComboBoxValueCategory;
    private javax.swing.JComboBox<String> jComboBoxValueCustomerId;
    private javax.swing.JComboBox<String> jComboBoxValueEmployeeId;
    private com.toedter.calendar.JDateChooser jDateChooserValueOrderDate;
    private javax.swing.JLabel jLabelProductImage;
    private javax.swing.JLabel jLabelProductImage1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCart;
    private javax.swing.JPanel jPanelOrderPay;
    private javax.swing.JPanel jPanelProductItem;
    private javax.swing.JPanel jPanelProductItem1;
    private javax.swing.JPanel jPanelScanCode;
    private javax.swing.JPanel jPanel_orderInfomation;
    private javax.swing.JScrollPane jScrollPaneCart;
    private javax.swing.JScrollPane jScrollPaneListProduct;
    private javax.swing.JTable jTableCart;
    private javax.swing.JTextField jTextFieldValueCustomerMoneyGive;
    private javax.swing.JTextField jTextFieldValueNote;
    private javax.swing.JTextField jTextFieldValueSearchProduct;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblAuthor1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerMoneyGive;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblMustPay;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblProductId;
    private javax.swing.JLabel lblProductId1;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductName1;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblProductPrice1;
    private javax.swing.JLabel lblProductQuantity;
    private javax.swing.JLabel lblProductQuantity1;
    private javax.swing.JLabel lblReturnMoneyToCustomer;
    private javax.swing.JLabel lblSearchProduct;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblUnit1;
    private javax.swing.JLabel lblUnit2;
    private javax.swing.JLabel lblUnit3;
    private javax.swing.JLabel lblUnit4;
    private javax.swing.JLabel lblUnit5;
    private javax.swing.JLabel lblUnit6;
    private javax.swing.JLabel lblUnit7;
    private javax.swing.JLabel lblVAlueAuthor;
    private javax.swing.JLabel lblVAlueAuthor1;
    private javax.swing.JLabel lblValueCustomerName;
    private javax.swing.JLabel lblValueDiscount;
    private javax.swing.JLabel lblValueMustPay;
    private javax.swing.JLabel lblValueOrderId;
    private javax.swing.JLabel lblValueProductId;
    private javax.swing.JLabel lblValueProductId1;
    private javax.swing.JLabel lblValueProductName;
    private javax.swing.JLabel lblValueProductName1;
    private javax.swing.JLabel lblValueProductPrice;
    private javax.swing.JLabel lblValueProductPrice1;
    private javax.swing.JLabel lblValueProductQuantity;
    private javax.swing.JLabel lblValueProductQuantity1;
    private javax.swing.JLabel lblValueReturnMoneyToCustomer;
    private javax.swing.JLabel lblValueTotalAmount;
    private javax.swing.JPanel panelListProduct;
    // End of variables declaration//GEN-END:variables
}
