/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import Dao.AccountDAOImpl;
import entity.Account;
import connectDB.ConnectDB;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VONG VINH LOI
 */
public class JpannelAccount extends javax.swing.JPanel {
    private ButtonGroup btgroup;
    private DefaultTableModel modelAccount;
    private AccountDAOImpl accountDao;
    /**
     * Creates new form QlTaiKhoan
     * @throws java.sql.SQLException
     */
    public JpannelAccount() throws SQLException {
        modelAccount = new DefaultTableModel();
        initComponents();
        ConnectDB.getInstance().connect();
        loadData();
        svgAdd.setSvgImage("add.svg", 30, 30);
        svgEdit.setSvgImage("edit.svg", 25, 25);
        svgDelete.setSvgImage("delete.svg", 30, 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpAccountManagerment = new javax.swing.JPanel();
        jbAccountManagerment = new javax.swing.JLabel();
        jbFunction = new javax.swing.JPanel();
        jbStatus = new javax.swing.JLabel();
        jbEmployeeId = new javax.swing.JLabel();
        jbUserName = new javax.swing.JLabel();
        jbPassword = new javax.swing.JLabel();
        jbRole = new javax.swing.JLabel();
        radLock = new javax.swing.JRadioButton();
        btgroup = new ButtonGroup();
        radNormal = new javax.swing.JRadioButton();
        jcbEmployeeId = new javax.swing.JComboBox<>();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jcbRole = new javax.swing.JComboBox<>();
        jpAdd = new customLib.roundedPanel();
        jbAdd = new javax.swing.JLabel();
        svgAdd = new customLib.SVGImage();
        jpEdit = new customLib.roundedPanel();
        jbEdit = new javax.swing.JLabel();
        svgEdit = new customLib.SVGImage();
        jpDelete = new customLib.roundedPanel();
        jbDelete = new javax.swing.JLabel();
        svgDelete = new customLib.SVGImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelAccount = new DefaultTableModel();
        tableAccount = new JTable(modelAccount);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 720));
        setLayout(new java.awt.BorderLayout());

        jpAccountManagerment.setMinimumSize(new java.awt.Dimension(351, 50));
        jpAccountManagerment.setLayout(new java.awt.BorderLayout());

        jbAccountManagerment.setBackground(new java.awt.Color(255, 255, 255));
        jbAccountManagerment.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jbAccountManagerment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbAccountManagerment.setText("ACCOUNT MANAGERMENT");
        jbAccountManagerment.setPreferredSize(new java.awt.Dimension(351, 55));
        jpAccountManagerment.add(jbAccountManagerment, java.awt.BorderLayout.CENTER);

        add(jpAccountManagerment, java.awt.BorderLayout.PAGE_START);

        jbFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbStatus.setText("Status");
        jbFunction.add(jbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, 30));

        jbEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEmployeeId.setText("Employee ID:");
        jbFunction.add(jbEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 100, 30));

        jbUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbUserName.setText("User name:");
        jbFunction.add(jbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 30));

        jbPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbPassword.setText("Password:");
        jbFunction.add(jbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, 30));

        jbRole.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbRole.setText("Role:");
        jbFunction.add(jbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, 30));

        radLock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radLock.setText("Lock");
        jbFunction.add(radLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 30));

        btgroup.add(radLock);
        btgroup.add(radNormal);
        radNormal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radNormal.setText("Normal");
        radNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNormalActionPerformed(evt);
            }
        });
        jbFunction.add(radNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, 30));

        jcbEmployeeId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbEmployeeId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbFunction.add(jcbEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 180, 30));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbFunction.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 180, 30));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbFunction.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 180, 30));

        jcbRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lí"}));
        jcbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoleActionPerformed(evt);
            }
        });
        jbFunction.add(jcbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 180, 30));

        jpAdd.setBackground(new java.awt.Color(255, 255, 255));
        jpAdd.setRoundedBottomLeft(10);
        jpAdd.setRoundedBottomRight(10);
        jpAdd.setRoundedTopLeft(10);
        jpAdd.setRoundedTopRight(10);
        jpAdd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAdd.setText("Add");
        jpAdd.add(jbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 40));

        svgAdd.setText(" ");
        jpAdd.add(svgAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 30, 30));

        jbFunction.add(jpAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 40));

        jpEdit.setBackground(new java.awt.Color(255, 255, 255));
        jpEdit.setRoundedBottomLeft(10);
        jpEdit.setRoundedBottomRight(10);
        jpEdit.setRoundedTopLeft(10);
        jpEdit.setRoundedTopRight(10);
        jpEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbEdit.setText("Edit");
        jpEdit.add(jbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 40));

        svgEdit.setText(" ");
        jpEdit.add(svgEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 30, 30));

        jbFunction.add(jpEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, 40));

        jpDelete.setBackground(new java.awt.Color(255, 255, 255));
        jpDelete.setRoundedBottomLeft(10);
        jpDelete.setRoundedBottomRight(10);
        jpDelete.setRoundedTopLeft(10);
        jpDelete.setRoundedTopRight(10);
        jpDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbDelete.setText("Delete");
        jpDelete.add(jbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 40));

        svgDelete.setText(" ");
        jpDelete.add(svgDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 30, 30));

        jbFunction.add(jpDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 100, 40));

        add(jbFunction, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 500));

        modelAccount.addColumn("Ma nhân viên");
        modelAccount.addColumn("Tên tài khoản");
        modelAccount.addColumn("Mật khẩu");
        modelAccount.addColumn("Quyền");
        modelAccount.addColumn("Trạng thái");
        tableAccount.setModel(modelAccount);
        jScrollPane1.setViewportView(tableAccount);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void radNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNormalActionPerformed

    private void jcbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRoleActionPerformed
    private void loadData()
    {
        accountDao = new AccountDAOImpl();
        for(Account acc : accountDao.getAllHocVien())
        {
            Object[] row = {acc.getAccountID(),acc.getUserName(),acc.getPassword(),acc.getRole(),changeStatus(acc.isStatus())};
            modelAccount.addRow(row);
        }
    }
    private String changeStatus(boolean t)
    {
        if(t==true)
        {
            return "Bình thường";
        }
        else 
        {
            return "Khoá";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbAccountManagerment;
    private javax.swing.JLabel jbAdd;
    private javax.swing.JLabel jbDelete;
    private javax.swing.JLabel jbEdit;
    private javax.swing.JLabel jbEmployeeId;
    private javax.swing.JPanel jbFunction;
    private javax.swing.JLabel jbPassword;
    private javax.swing.JLabel jbRole;
    private javax.swing.JLabel jbStatus;
    private javax.swing.JLabel jbUserName;
    private javax.swing.JComboBox<String> jcbEmployeeId;
    private javax.swing.JComboBox<String> jcbRole;
    private javax.swing.JPanel jpAccountManagerment;
    private customLib.roundedPanel jpAdd;
    private customLib.roundedPanel jpDelete;
    private customLib.roundedPanel jpEdit;
    private javax.swing.JRadioButton radLock;
    private javax.swing.JRadioButton radNormal;
    private customLib.SVGImage svgAdd;
    private customLib.SVGImage svgDelete;
    private customLib.SVGImage svgEdit;
    private javax.swing.JTable tableAccount;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
