/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.TaiKhoanDAO;
import entity.TaiKhoan;
import connectDB.ConnectDB;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VONG VINH LOI
 */
public class JPanel_TaiKhoan extends javax.swing.JPanel {

    private ButtonGroup btgroup;
    private final DefaultTableModel modelAccount;
    private TaiKhoanDAO accountDao;

    public JPanel_TaiKhoan() throws SQLException {

        initComponents();
        ConnectDB.getInstance().connect();
        modelAccount = (DefaultTableModel) tableAccount.getModel();
        loadData();
        svgEdit.setSvgImage("edit.svg", 35, 35);
        svgDelete.setSvgImage("delete.svg", 40, 40);

        svgRefresh.setSvgImage("refresh.svg", 35, 35);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpAccountManagerment = new javax.swing.JPanel();
        jbAccountManagerment = new javax.swing.JLabel();
        jbFunction = new javax.swing.JPanel();
        jbStatus = new javax.swing.JLabel();
        jbEmployeeId = new javax.swing.JLabel();
        jbPassword = new javax.swing.JLabel();
        jbRole = new javax.swing.JLabel();
        radLock = new javax.swing.JRadioButton();
        btgroup = new ButtonGroup();
        radNormal = new javax.swing.JRadioButton();
        jcbEmployeeId = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        jcbRole = new javax.swing.JComboBox<>();
        jpEdit = new util.JPanelRounded();
        jbEdit = new javax.swing.JLabel();
        svgEdit = new util.SVGImage();
        jpDelete = new util.JPanelRounded();
        jbDelete = new javax.swing.JLabel();
        svgDelete = new util.SVGImage();
        jbLamMoi = new util.JPanelRounded();
        jbRefresh = new javax.swing.JLabel();
        svgRefresh = new util.SVGImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 720));
        setLayout(new java.awt.BorderLayout());

        jpAccountManagerment.setMinimumSize(new java.awt.Dimension(351, 50));
        jpAccountManagerment.setLayout(new java.awt.BorderLayout());

        jbAccountManagerment.setBackground(new java.awt.Color(255, 255, 255));
        jbAccountManagerment.setFont(new java.awt.Font("Roboto Black", 0, 40)); // NOI18N
        jbAccountManagerment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbAccountManagerment.setText("QUẢN LÝ TÀI KHOẢN");
        jbAccountManagerment.setPreferredSize(new java.awt.Dimension(351, 70));
        jpAccountManagerment.add(jbAccountManagerment, java.awt.BorderLayout.CENTER);

        add(jpAccountManagerment, java.awt.BorderLayout.PAGE_START);

        jbFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbStatus.setText("Trạng thái:");
        jbFunction.add(jbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 40));

        jbEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbEmployeeId.setText("Mã nhân viên:");
        jbFunction.add(jbEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 40));

        jbPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbPassword.setText("Mật khẩu:");
        jbFunction.add(jbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, 40));

        jbRole.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbRole.setText("Quyền:");
        jbFunction.add(jbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 40));

        radLock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radLock.setText("Khoá");
        jbFunction.add(radLock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, 40));

        btgroup.add(radLock);
        btgroup.add(radNormal);
        radNormal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radNormal.setText("Bình thường");
        radNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radNormalActionPerformed(evt);
            }
        });
        jbFunction.add(radNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, 40));

        jcbEmployeeId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbEmployeeId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jbFunction.add(jcbEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 180, 40));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbFunction.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 300, 40));

        jcbRole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Quản lí"}));
        jcbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoleActionPerformed(evt);
            }
        });
        jbFunction.add(jcbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 230, 40));

        jpEdit.setBackground(new java.awt.Color(255, 255, 255));
        jpEdit.setRoundedBottomLeft(10);
        jpEdit.setRoundedBottomRight(10);
        jpEdit.setRoundedTopLeft(10);
        jpEdit.setRoundedTopRight(10);
        jpEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbEdit.setText("Sửa");
        jpEdit.add(jbEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 50));

        svgEdit.setText(" ");
        jpEdit.add(svgEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 40, 40));

        jbFunction.add(jpEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, 50));

        jpDelete.setBackground(new java.awt.Color(255, 255, 255));
        jpDelete.setRoundedBottomLeft(10);
        jpDelete.setRoundedBottomRight(10);
        jpDelete.setRoundedTopLeft(10);
        jpDelete.setRoundedTopRight(10);
        jpDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbDelete.setText("Xoá");
        jpDelete.add(jbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 50));

        svgDelete.setText(" ");
        jpDelete.add(svgDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 40, 40));

        jbFunction.add(jpDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 150, 50));

        jbLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        jbLamMoi.setRoundedBottomLeft(10);
        jbLamMoi.setRoundedBottomRight(10);
        jbLamMoi.setRoundedTopLeft(10);
        jbLamMoi.setRoundedTopRight(10);
        jbLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbLamMoiMouseClicked(evt);
            }
        });
        jbLamMoi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbRefresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbRefresh.setText("Làm mới");
        jbLamMoi.add(jbRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 50));

        svgRefresh.setText(" ");
        jbLamMoi.add(svgRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 40, 40));

        jbFunction.add(jbLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 150, 50));

        add(jbFunction, java.awt.BorderLayout.CENTER);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 520));

        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên tài khoản", "Mật khẩu", "Quyền", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAccount);

        add(jScrollPane1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void radNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radNormalActionPerformed

    private void jcbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRoleActionPerformed

    private void jbLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLamMoiMouseClicked

    }//GEN-LAST:event_jbLamMoiMouseClicked
    private void loadData() {
        accountDao = new TaiKhoanDAO();
        for (TaiKhoan tk : accountDao.getAllTaiKhoan()) {
            Object[] row = {tk.getMaTK(), tk.getTenDangNhap(), tk.getMatKhau(), tk.getQuyen(), tk.getTrangThaiTaiKhoan()};
            modelAccount.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbAccountManagerment;
    private javax.swing.JLabel jbDelete;
    private javax.swing.JLabel jbEdit;
    private javax.swing.JLabel jbEmployeeId;
    private javax.swing.JPanel jbFunction;
    private util.JPanelRounded jbLamMoi;
    private javax.swing.JLabel jbPassword;
    private javax.swing.JLabel jbRefresh;
    private javax.swing.JLabel jbRole;
    private javax.swing.JLabel jbStatus;
    private javax.swing.JComboBox<String> jcbEmployeeId;
    private javax.swing.JComboBox<String> jcbRole;
    private javax.swing.JPanel jpAccountManagerment;
    private util.JPanelRounded jpDelete;
    private util.JPanelRounded jpEdit;
    private javax.swing.JRadioButton radLock;
    private javax.swing.JRadioButton radNormal;
    private util.SVGImage svgDelete;
    private util.SVGImage svgEdit;
    private util.SVGImage svgRefresh;
    private javax.swing.JTable tableAccount;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
